stages:
  - deploy

deploy:
  stage: deploy
  image: amazon/aws-cli:2.13.14
  script:
    - echo "Triggering AWS CodeBuild project..."
    - aws codebuild start-build --project-name $CODEBUILD_PROJECT_NAME
  only:
    - main
