name: Deploy Frontend to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger AWS CodeBuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger CodeBuild
        env:
          AWS_REGION: eu-central-1
          CODEBUILD_PROJECT_NAME: sofft-frontend-build # update if needed
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region $AWS_REGION
          aws codebuild start-build --project-name $CODEBUILD_PROJECT_NAME
